### PR TITLE
chore: Update to Closure Compiler v20161024

### PR DESCRIPTION
**Pull request by dpurp**

### CODE REVIEW

**Comment by gmoothart** [comment]
I don't see this version in Maven. This is where I usually check:
https://mvnrepository.com/artifact/com.google.javascript/closure-compiler

**Comment by dpurp** [comment]
Yes, it's available on Github, but not on Maven yet.  I emailed the Closure Compiler team to remind them.

**Comment by dpurp** [comment]
The release is now available on Maven, but has some clutz failures. :(

**Comment by rkirov** [comment]
superceded by  #422

**Pull request closed without merging**
