### PR TITLE
emit all externs

### LINKED ISSUE #205: don't skip closure browser apis externs that are not matched by lib.d.ts
for example - https://github.com/google/closure-compiler/blob/master/externs/browser/fileapi.js which is Chrome only and discontinued - http://caniuse.com/#search=filesystem

go through https://github.com/google/closure-compiler/tree/master/externs/browser and add unmatched files to a whitelist.

### PR DESCRIPTION
**Pull request by rkirov**
The strategy to not emit platform externs, because they are present in
lib.d.ts is error prone, because closure platform typings can widely
vary from lib.d.ts's versions. Even thought they target the same runtime
API, there are many design decisions (structuring interfaces, enums etc)
that cannot be easily reconciled within the tool.

This commit switches to emitting all closure externs, in order to allow
closures' types to typecheck against them.

Collisions are avoided by making sure all closure types are still in the
internal clutz namespace. That is closure Object interface is
ಠ_ಠ.clutz.Object, vs TS Object that is Object.

This drastic change required some reshuffling of the test
infrastructure. Removing the Syntax test that was a subset of
Usage test. Restrict to only single _with_externs test to run.

Fixes #205, #224, #226

BREAKING_CHANGE:
Previously, TS and Closure's Object were the same interface, thus one
can do:

var myObj: Object;
closureFunction(myObj);

Now this would be a type error because closureFunction expects ಠ_ಠ.clutz.Object.
The easiest workaround for now would be to do `closureFunction(<any> myObj);`

### CODE REVIEW

**Comment by rkirov** [comment]
Clearly this is very rough, but I want to hear your opinion before cleaning it up a bit. Also with its current state this gets us to 2 errors left of all of closure libs, so the hacks served their purpose to prove the concept.

**Comment by mprobst** [comment]
See my comment on the issue, let's keep the discussions there.

**Comment by rkirov** [comment]
I will reply on #224 tomorrow, but keep in mind that this fixes #205, #226 and #170 too.

**Comment by rkirov** [comment]
Superceeded by #256

**Pull request closed without merging**
